### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by CactoosB** [corsik/prestashop-clear-url-id#1]
I followed the instructions in the readme file, after translating it to spanish and english, but now i have eror 404 in every product page, every place that is without {id} now have 404.

i dont know how to give more detail appart from that i´m telling now.  The url now appears as this https://mypage.com/**index.php?controller=404** 

mod_security Apache is **off**
Friendly url is **on**
url multiview deactivation is **on**

i kindly ask for help in this.
Thank you in advance.

**Comment by corsik** [comment]
@CactoosB have you copied all the files in the override folder?

**Comment by augustedupin** [comment]
it doesn't work with products with attributes, right?

**Comment by corsik** [comment]
@augustedupin On my site I use this module perfectly with attributes

**Comment by augustedupin** [comment]
i copied all override files in override directory, it works on category and CMS pages but not in products with attributes it gives me the follow:
www.mysite.com/category-name/-{id_product}{product-name}html#/{id_product_attribute}-{product_attribute-name}

any idea? thank you!

**Comment by corsik** [comment]
@augustedupin these are my settings SEO and URLs http://joxi.ru/E2pd05dS7vo1M2 **_https://mysite.ru/accessories/noski-total-black-2-pary#/3-razmer-4_6_let_27_30sm_** and this URL works well
