### ISSUE TITLE
Пара предложений

### ISSUE THREAD

**Issue by Hedgehog85** [corsik/prestashop-clear-url-id#2]
Привет, спасибо большое найс работает на пс 1.7.5.1 . Было бы еще хорошо если бы можно было убрать из юрл комбинации товара. Т.е у меня если выбрать какую-то комбинацию выходит юрл типа website.com/product.html#/2186-brand_manufacturer-alpha_d3_teva_teva_israel/39-dosage_form-capsules/2187-package_size-025_mcg_30_pcs
И html еще чтоб можно было убирать. Он Убирается но тогда ошибка 404 на товарах. Даже среди платных плагинов искал не нашел чтобы это как-то фиксилось, хотя я их не покупал не пробовал, чисто по описаниям вроде только ид исправляют. А так спасибо конечно большое за бесплатный плагин, ид убирает уже здорово.

**Comment by corsik** [comment]
@Hedgehog85 Попробуйте выставить такие настройки
![image](https://user-images.githubusercontent.com/9282699/54276292-aa3bcc00-4595-11e9-987e-d6779220d067.png)

**Comment by Hedgehog85** [comment]
Да спс, если в путь к товару категорию включить то без html работает. Правда категория наверное даже больше юрл удлинняет чем ид, наверн тогда есть смысл rewrite категорий просто короче сделать. 

Еще сейчас попробовал, можно вместо категории в юрл товара что-то другое вставить, чтобы вышел юрл типа buy/{rewrite}. Так выходит короткий юрл тоже без хтмл и длинного реврайта категории. 

А можно как-то из юрла убрать вариации товара? Он оч сильно юрл удлинняет, раза в 2-3. Для сео наверное не критично тк на страницах есть canonical ссылки по умолчанию, но если кто-то захочет ссылку на товар расшарить то длинная ссылка это минус

**Comment by corsik** [comment]
> Еще сейчас попробовал, можно вместо категории в юрл товара что-то другое вставить, чтобы вышел юрл типа buy/{rewrite}. Так выходит короткий юрл тоже без хтмл и длинного реврайта категории.

Поиск товара происходит по значению **rewrite**, по этому вы можете вставлять любую строку перед ним.
>А можно как-то из юрла убрать вариации товара? Он оч сильно юрл удлинняет, раза в 2-3. Для сео наверное не критично тк на страницах есть canonical ссылки по умолчанию, но если кто-то захочет ссылку на товар расшарить то длинная ссылка это минус

Вариации товара идут за хештегом # и не должны влиять на длину url при ранжирование

**Comment by Hedgehog85** [comment]
> Вариации товара идут за хештегом # и не должны влиять на длину url при ранжирование

Ну да влиять не должно, но если допустим чел какой-то хочет расшарить ссылку на товар, то короткий юрл лучше, я про это. Но энивей норм, главное id и хтмл убрать. А есть у тебя может вебмани какой, я задонатил бы немношк за труды?

**Comment by corsik** [comment]
@Hedgehog85 Давно хотел создать, всё руки не доходили
[![ko-fi](https://corsik.ru/coffe.png)](https://www.paypal.me/corsik/3)

**Comment by Hedgehog85** [comment]
Скинул 600р, мне пейпал написал 60000 успешно отправлено лол. Аж ладошки вспотели 60к целых че за баг такой, но проверил вроде норм отправило 600р

**Comment by corsik** [comment]
@Hedgehog85 спасибо, 2 нуля это видно копейки. Странно, если запятой не было.
