### ISSUE TITLE
[Question] Brands and Product URL change

### ISSUE THREAD

**Issue by njcalvo** [corsik/prestashop-clear-url-id#3]
Hi, really good job, thanks!
I want to know if it's possible to change brand to {rewrite} (similar to Categories) and product to {rewrite}-{id}{-:id_product_attribute}.html
Thanks and greetings

**Comment by corsik** [comment]
@NJCalvo Thank you, unfortunately for brands you need a keyword such as brands/{rewrite}, try the products for yourself.

**Comment by njcalvo** [comment]
Ok thanks!
