### ISSUE TITLE
Can't install, zip error

### ISSUE THREAD

**Issue by marklb98** [corsik/prestashop-clear-url-id#4]
Hi, i am trying to insstall your module, but every time a try to install i says that the zip file is not well format

could you please help me

thanks

**Comment by marklb98** [comment]
PS

Prestashop version 1.7.5.2

**Comment by corsik** [comment]
Hi, @marklb98 
If you are downloading from github
1. Clone or download
2. Unzip and rename the prestashop-clear-url-id-master folder to crk_urls_clear
3. Archive crk_urls_clear

**Comment by marklb98** [comment]
Ok

Thanks it works

Great Module
